# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/boop/Packages/Linux_Unreal_Engine_5.5.1

TARGETS = \
	Winter_MelonJam-Android-DebugGame  \
	Winter_MelonJam-Android-Development  \
	Winter_MelonJam-Android-Shipping  \
	Winter_MelonJam-Linux-DebugGame  \
	Winter_MelonJam-Linux-Development  \
	Winter_MelonJam-Linux-Shipping  \
	Winter_MelonJam-LinuxArm64-DebugGame  \
	Winter_MelonJam-LinuxArm64-Development  \
	Winter_MelonJam-LinuxArm64-Shipping  \
	Winter_MelonJam \
	Winter_MelonJamEditor-Linux-DebugGame  \
	Winter_MelonJamEditor-Linux-Development  \
	Winter_MelonJamEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Winter_MelonJamEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Winter_MelonJamEditor-Linux-Debug


Winter_MelonJam-Android-DebugGame:
	 $(BUILD) Winter_MelonJam Android DebugGame  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJam-Android-Development:
	 $(BUILD) Winter_MelonJam Android Development  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJam-Android-Shipping:
	 $(BUILD) Winter_MelonJam Android Shipping  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJam-Linux-DebugGame:
	 $(BUILD) Winter_MelonJam Linux DebugGame  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJam-Linux-Development:
	 $(BUILD) Winter_MelonJam Linux Development  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJam-Linux-Shipping:
	 $(BUILD) Winter_MelonJam Linux Shipping  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJam-LinuxArm64-DebugGame:
	 $(BUILD) Winter_MelonJam LinuxArm64 DebugGame  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJam-LinuxArm64-Development:
	 $(BUILD) Winter_MelonJam LinuxArm64 Development  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJam-LinuxArm64-Shipping:
	 $(BUILD) Winter_MelonJam LinuxArm64 Shipping  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJam: Winter_MelonJam-Linux-Development

Winter_MelonJamEditor-Linux-DebugGame:
	 $(BUILD) Winter_MelonJamEditor Linux DebugGame  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJamEditor-Linux-Development:
	 $(BUILD) Winter_MelonJamEditor Linux Development  -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" $(ARGS)

Winter_MelonJamEditor: Winter_MelonJamEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/boop/Documents/Unreal Projects/Winter_MelonJam/Winter_MelonJam.uproject" -Game 

.PHONY: $(TARGETS)
